### ISSUE TITLE
Allow specifying a "--yes" option for all actions individually

### ISSUE THREAD

**Issue by dlemfh** [hartwork/git-delete-merged-branches#102]
**Request:**

For all actions

- `git remote update --prune`
- `git pull --ff-only`
- delete local branch(es)
- delete remote branch(es):

would you be willing to provide separate "--yes" options for each action?

**Use case:**

I want to automatically confirm the first 3 actions, while not running the last (`delete remote branches`) action.

For that, I currently use the following alias:
```bash
alias "gdmb"="printf 'y\ny\ny\nn\n' | git-delete-merged-branches --effort=3"
```

But the alias command does not work as expected **when there are no local branches to delete**.
When there are no local branches to delete, the program does not prompt the question for deleting local branches, and so the 3rd `y` ends up being a reply to the `delete remote branches` prompt instead.

Is there a better way for me to configure my alias?

Would you be willing to upgrade the program to take individual "--yes" options per each action?

**Comment by hartwork** [comment]
Hi @dlemfh, 

I think I understand your scenario and what you are asking. I see two separate aspects here:
1. Need for finer control than a universal `--yes` inside git-delete-merged-branches to make things easier,
2. How to best skip deletion of merged remote branches some of the time when `--yes` while all there is, i.e. options for a robust workaround for the moment,

For (1) I'm still thinking, and I should maybe do more of that before trying to really reply on that aspect.

Just brainstorming, for (2) right now I can think of:
- a) Having two local clones around, one configured to delete remote branches and only used occasionally, the other configured to *not* delete remote branches and used most of the time.
- b) Potentially the same but using `git worktree` rather than two independent clones.
- c) Leveraging `git -c "<name>=<value>"` (https://stackoverflow.com/a/19841156/11626624) and making `git-delete-merged-branches` use that command rather than plain `git`, e.g. through `$PATH`.

What do you think?

PS: Feature request #84 seems related by more than just a bit.

**Comment by hartwork** [comment]
> I didn't realize there's a configuration to "not delete remote branches". Did a google search and found `git config receive.denyDeletes true`, but doesn't seem to be working for me.. Did you have something else in mind?

When you enable a Git remote for deletion at `git-delete-merged-branches --configure` time, technically git-delete-merged-branches creates Git config entries named `remote.<remote_name>.dmb-enabled=true` for each enabled remote . So `git -c remote.remote123.dmb-enabled=false [..]` would exclude `remote123` when `git-delete-merged-branches` invokes Git like that consistently from `${PATH}`. It's surely more of a hack than anything else.

There's one more hack that I can think of: Create a branch that will sure be deleted right before the call, e.g. `git branch merged-to-main main` and then the `printf` hack of yours would be "stable".

> Any valid option for my use case is fine for me, but IMHO users would benefit from a finer control rather than a universal `--yes`!

I understand, let me digest it a bit more.

**Comment by dlemfh** [comment]
> When you enable a Git remote for deletion at git-delete-merged-branches --configure time

Ah!! Just realized `git-delete-merged-branches --configure` already provides a way to not delete any remote branches (by unchecking all remote origins).

I've been blindly checking all the boxes for remote origins.. my bad..

Thanks for the thorough explanations! Gave me an insight into how well thought out this program is. 👍

For me personally, my use case is covered here (by unchecking all remote origins for deletion of branches).
So please feel free to close and/or further investigate this enhancement proposal.

Thanks again @hartwork!

**Comment by hartwork** [comment]
@dlemfh thanks for the update, glad to hear!

**Comment by hartwork** [comment]
Closing as "status quo turned out good enough for the moment"…

**Comment by rnestler** [comment]
> Need for finer control than a universal --yes inside git-delete-merged-branches to make things easier,

@hartwork I think this would be nice. I always answer yes to the first two questions ("git remote update --prune", and "git pull --ff-only"), but take a closer look before deleting local and especially remote branches.
